//! TypeScript client generation.
//!
//! The other half of the frontend answer. `app.page()` covers server-rendered
//! HTML; this covers the SPA case, and both are projections of the same route
//! table — so a route added in `api.py` shows up in the typed client without
//! anyone writing an interface by hand.
//!
//! Output is a single dependency-free `.ts` file using `fetch`. No runtime
//! package to version-skew against the server that generated it.

use crate::manifest::{Manifest, Op, Route};
use std::fmt::Write;

pub fn generate(m: &Manifest) -> String {
    let mut out = String::new();

    let _ = writeln!(
        out,
        r#"// Generated by `webcortex typegen` from {name} v{version}.
// Do not edit: regenerate instead, so the client cannot drift from the server.

export type Json = string | number | boolean | null | Json[] | {{ [k: string]: Json }};

export class WebCortexError extends Error {{
  constructor(
    readonly status: number,
    readonly body: unknown,
    message: string,
  ) {{
    super(message);
    this.name = "WebCortexError";
  }}
}}

export interface ClientOptions {{
  baseUrl?: string;
  /** Sent as `x-api-key`. */
  apiKey?: string;
  /** Sent as `Authorization: Bearer <token>`. May be async for refresh flows. */
  token?: string | (() => string | Promise<string>);
  fetch?: typeof fetch;
  /** Merged into every request; useful for tracing headers. */
  headers?: Record<string, string>;
}}
"#,
        name = m.name,
        version = m.version
    );

    // Interfaces first, so operation signatures can reference them by name.
    // Every named type is emitted at top level rather than inlined: a
    // multi-line object type spliced into `Promise<...>` is not valid
    // TypeScript, and object schemas are routinely multi-line.
    for r in &m.routes {
        if is_internal(r) {
            continue;
        }
        if let Some(schema) = &r.input_schema {
            if schema.get("properties").and_then(|p| p.as_object()).is_some_and(|p| !p.is_empty()) {
                let _ = writeln!(
                    out,
                    "export interface {}Params {}\n",
                    pascal(&r.tool_name()),
                    ts_object(schema, 0)
                );
            }
        }
        if let Some(shape) = result_object_schema(r) {
            let _ = writeln!(
                out,
                "export interface {}Result {}\n",
                pascal(&r.tool_name()),
                ts_object(shape, 0)
            );
        }
    }

    let _ = writeln!(
        out,
        r#"export class WebCortexClient {{
  private readonly baseUrl: string;
  private readonly opts: ClientOptions;
  private readonly doFetch: typeof fetch;

  constructor(opts: ClientOptions = {{}}) {{
    this.opts = opts;
    this.baseUrl = (opts.baseUrl ?? "").replace(/\/$/, "");
    this.doFetch = opts.fetch ?? globalThis.fetch.bind(globalThis);
  }}

  private async headers(): Promise<Record<string, string>> {{
    const h: Record<string, string> = {{
      "content-type": "application/json",
      ...this.opts.headers,
    }};
    if (this.opts.apiKey) h["x-api-key"] = this.opts.apiKey;
    if (this.opts.token) {{
      const t = typeof this.opts.token === "function" ? await this.opts.token() : this.opts.token;
      if (t) h["authorization"] = `Bearer ${{t}}`;
    }}
    return h;
  }}

  private async request<T>(
    method: string,
    path: string,
    params?: Record<string, unknown>,
    hasBody = false,
  ): Promise<T> {{
    let url = this.baseUrl + path;
    const query = new URLSearchParams();
    const body: Record<string, unknown> = {{}};

    for (const [k, v] of Object.entries(params ?? {{}})) {{
      if (v === undefined) continue;
      const token = `{{${{k}}}}`;
      if (url.includes(token)) {{
        url = url.replace(token, encodeURIComponent(String(v)));
      }} else if (hasBody) {{
        body[k] = v;
      }} else {{
        query.set(k, String(v));
      }}
    }}

    const qs = query.toString();
    const res = await this.doFetch(qs ? `${{url}}?${{qs}}` : url, {{
      method,
      headers: await this.headers(),
      body: hasBody ? JSON.stringify(body) : undefined,
    }});

    const text = await res.text();
    const parsed = text ? (JSON.parse(text) as unknown) : null;
    if (!res.ok) {{
      const msg =
        (parsed as {{ error?: {{ message?: string }} }})?.error?.message ?? res.statusText;
      throw new WebCortexError(res.status, parsed, msg);
    }}
    return parsed as T;
  }}
"#
    );

    for r in &m.routes {
        if is_internal(r) {
            continue;
        }
        let name = camel(&r.tool_name());
        let has_params = r
            .input_schema
            .as_ref()
            .and_then(|s| s.get("properties"))
            .and_then(|p| p.as_object())
            .is_some_and(|p| !p.is_empty());
        let has_body = matches!(r.method.as_str(), "POST" | "PUT" | "PATCH");
        let ret = result_type(r);

        let doc = if r.description.is_empty() { &r.summary } else { &r.description };
        if !doc.is_empty() {
            let _ = writeln!(out, "  /** {} */", doc.lines().next().unwrap_or("").trim());
        }

        if has_params {
            let _ = writeln!(
                out,
                "  {name}(params: {p}Params): Promise<{ret}> {{\n    return this.request<{ret}>({m:?}, {path:?}, params as Record<string, unknown>, {body});\n  }}\n",
                p = pascal(&r.tool_name()),
                m = r.method,
                path = r.path,
                body = has_body,
            );
        } else {
            let _ = writeln!(
                out,
                "  {name}(): Promise<{ret}> {{\n    return this.request<{ret}>({m:?}, {path:?}, undefined, {body});\n  }}\n",
                m = r.method,
                path = r.path,
                body = has_body,
            );
        }
    }

    let _ = writeln!(out, "}}\n");
    let _ = writeln!(
        out,
        "export const createClient = (opts?: ClientOptions) => new WebCortexClient(opts);"
    );

    out
}

/// Pages and static files are not part of the JSON API surface.
fn is_internal(r: &Route) -> bool {
    matches!(r.op, Op::Page { .. } | Op::Files { .. })
}

/// The object schema behind a route's result, unwrapping a top-level array.
/// `None` when the result is a scalar or unspecified, which needs no interface.
fn result_object_schema(r: &Route) -> Option<&serde_json::Value> {
    let schema = r.output_schema.as_ref()?;
    let inner = match schema.get("type").and_then(|t| t.as_str()) {
        Some("array") => schema.get("items")?,
        _ => schema,
    };
    let has_props = inner
        .get("properties")
        .and_then(|p| p.as_object())
        .is_some_and(|p| !p.is_empty());
    has_props.then_some(inner)
}

/// The return type written into a method signature. Always a single token, so
/// it can never break the line it is spliced into.
fn result_type(r: &Route) -> String {
    let named = format!("{}Result", pascal(&r.tool_name()));
    match result_object_schema(r) {
        Some(_) => {
            let is_array = r
                .output_schema
                .as_ref()
                .and_then(|s| s.get("type"))
                .and_then(|t| t.as_str())
                == Some("array");
            if is_array { format!("{named}[]") } else { named }
        }
        None => match r.output_schema.as_ref() {
            Some(s) => {
                let t = ts_type(s, 0);
                // Anything that wrapped onto multiple lines is unusable inline.
                if t.contains('\n') { "Json".into() } else { t }
            }
            None => "Json".into(),
        },
    }
}

fn ts_object(schema: &serde_json::Value, depth: usize) -> String {
    let indent = "  ".repeat(depth + 1);
    let close = "  ".repeat(depth);
    let Some(props) = schema.get("properties").and_then(|p| p.as_object()) else {
        return "{ [k: string]: Json }".into();
    };
    let required: Vec<&str> = schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();

    let mut out = String::from("{\n");
    for (name, spec) in props {
        let optional = if required.contains(&name.as_str()) { "" } else { "?" };
        if let Some(desc) = spec.get("description").and_then(|d| d.as_str()) {
            let _ = writeln!(out, "{indent}/** {desc} */");
        }
        let _ = writeln!(out, "{indent}{}{}: {};", ident(name), optional, ts_type(spec, depth + 1));
    }
    let _ = write!(out, "{close}}}");
    out
}

fn ts_type(schema: &serde_json::Value, depth: usize) -> String {
    if let Some(values) = schema.get("enum").and_then(|e| e.as_array()) {
        let variants: Vec<String> = values
            .iter()
            .map(|v| match v {
                serde_json::Value::String(s) => format!("{s:?}"),
                other => other.to_string(),
            })
            .collect();
        return variants.join(" | ");
    }

    let nullable = schema.get("nullable").and_then(|n| n.as_bool()).unwrap_or(false);
    let base = match schema.get("type").and_then(|t| t.as_str()) {
        Some("string") => "string".to_string(),
        Some("integer") | Some("number") => "number".to_string(),
        Some("boolean") => "boolean".to_string(),
        Some("null") => "null".to_string(),
        Some("array") => {
            let item = schema
                .get("items")
                .map(|i| ts_type(i, depth))
                .unwrap_or_else(|| "Json".into());
            // Parenthesise unions so `A | B[]` cannot be misread.
            if item.contains(' ') {
                format!("({item})[]")
            } else {
                format!("{item}[]")
            }
        }
        Some("object") => {
            if schema.get("properties").is_some() {
                ts_object(schema, depth)
            } else {
                "{ [k: string]: Json }".into()
            }
        }
        _ => "Json".into(),
    };

    if nullable { format!("{base} | null") } else { base }
}

/// Quote a property name unless it is a valid bare TS identifier.
fn ident(name: &str) -> String {
    let valid = !name.is_empty()
        && !name.chars().next().unwrap().is_ascii_digit()
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if valid { name.to_string() } else { format!("{name:?}") }
}

fn pascal(s: &str) -> String {
    s.split(['_', '-', ' '])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel(s: &str) -> String {
    let p = pascal(s);
    let mut c = p.chars();
    match c.next() {
        Some(f) => f.to_ascii_lowercase().to_string() + c.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn manifest(routes: serde_json::Value) -> Manifest {
        serde_json::from_value(json!({"name": "t", "routes": routes})).expect("manifest")
    }

    #[test]
    fn emits_a_method_per_route() {
        let m = manifest(json!([{
            "id": 0, "method": "GET", "path": "/books",
            "op": {"kind": "static", "body": []},
            "tool": {"expose": true, "name": "list_books"}
        }]));
        let ts = generate(&m);
        assert!(ts.contains("listBooks("), "missing method:\n{ts}");
        assert!(ts.contains("\"GET\", \"/books\""));
    }

    #[test]
    fn params_become_a_typed_interface() {
        let m = manifest(json!([{
            "id": 0, "method": "GET", "path": "/books/{id}",
            "op": {"kind": "static", "body": {}},
            "tool": {"expose": true, "name": "get_book"},
            "input_schema": {
                "type": "object",
                "properties": {"id": {"type": "integer"}, "verbose": {"type": "boolean"}},
                "required": ["id"]
            }
        }]));
        let ts = generate(&m);
        assert!(ts.contains("export interface GetBookParams"));
        assert!(ts.contains("id: number;"), "required field must not be optional:\n{ts}");
        assert!(ts.contains("verbose?: boolean;"), "optional field must be optional:\n{ts}");
    }

    #[test]
    fn nullable_and_enum_types_render() {
        let m = manifest(json!([{
            "id": 0, "method": "GET", "path": "/x",
            "op": {"kind": "static", "body": {}},
            "input_schema": {"type": "object", "properties": {
                "note": {"type": "string", "nullable": true},
                "mode": {"enum": ["a", "b"]}
            }}
        }]));
        let ts = generate(&m);
        assert!(ts.contains("string | null"));
        assert!(ts.contains(r#""a" | "b""#));
    }

    #[test]
    fn pages_and_static_files_are_excluded_from_the_api_client() {
        let m = manifest(json!([
            {"id": 0, "method": "GET", "path": "/page",
             "op": {"kind": "page", "template": "x.html"}},
            {"id": 1, "method": "GET", "path": "/assets/{*path}",
             "op": {"kind": "files", "dir": "."}}
        ]));
        let ts = generate(&m);
        assert!(!ts.contains("/page"), "html page leaked into the API client");
        assert!(!ts.contains("/assets"), "static route leaked into the API client");
    }

    #[test]
    fn identifiers_that_are_not_valid_ts_get_quoted() {
        let m = manifest(json!([{
            "id": 0, "method": "GET", "path": "/x",
            "op": {"kind": "static", "body": {}},
            "input_schema": {"type": "object", "properties": {"weird-name": {"type": "string"}}}
        }]));
        assert!(generate(&m).contains(r#""weird-name""#));
    }

    #[test]
    fn arrays_of_unions_are_parenthesised() {
        let schema = json!({"type": "array", "items": {"type": "string", "nullable": true}});
        assert_eq!(ts_type(&schema, 0), "(string | null)[]");
    }

    #[test]
    fn write_methods_send_a_body() {
        let m = manifest(json!([{
            "id": 0, "method": "POST", "path": "/books",
            "op": {"kind": "static", "body": {}},
            "input_schema": {"type": "object", "properties": {"title": {"type": "string"}}}
        }]));
        let ts = generate(&m);
        assert!(ts.contains("\"POST\", \"/books\", params as Record<string, unknown>, true"));
    }

    #[test]
    fn method_signatures_are_always_single_line() {
        // Regression: object output schemas used to be inlined into
        // `Promise<...>`, splicing a multi-line type into a signature and
        // producing TypeScript that does not parse.
        let m = manifest(json!([{
            "id": 0, "method": "GET", "path": "/books",
            "op": {"kind": "static", "body": []},
            "tool": {"expose": true, "name": "list_books"},
            "output_schema": {"type": "array", "items": {
                "type": "object",
                "properties": {"id": {"type": "integer"}, "title": {"type": "string"}}
            }}
        }]));
        let ts = generate(&m);
        let sig = ts
            .lines()
            .find(|l| l.contains("listBooks("))
            .expect("method is emitted");
        assert!(sig.trim_end().ends_with('{'), "signature wrapped: {sig}");
        assert!(sig.contains("Promise<ListBooksResult[]>"), "got: {sig}");
        assert!(ts.contains("export interface ListBooksResult {"));
    }

    #[test]
    fn braces_balance_in_generated_output() {
        let m = manifest(json!([{
            "id": 0, "method": "POST", "path": "/books",
            "op": {"kind": "static", "body": {}},
            "input_schema": {"type": "object", "properties": {"title": {"type": "string"}}},
            "output_schema": {"type": "object", "properties": {
                "id": {"type": "integer"},
                "nested": {"type": "object", "properties": {"a": {"type": "string"}}}
            }}
        }]));
        let ts = generate(&m);
        let opens = ts.matches('{').count();
        let closes = ts.matches('}').count();
        assert_eq!(opens, closes, "unbalanced braces in generated client");
    }

    #[test]
    fn scalar_results_stay_inline() {
        let m = manifest(json!([{
            "id": 0, "method": "GET", "path": "/count",
            "op": {"kind": "static", "body": 0},
            "output_schema": {"type": "integer"}
        }]));
        assert!(generate(&m).contains("Promise<number>"));
    }

    #[test]
    fn name_casing_is_converted() {
        assert_eq!(pascal("list_books"), "ListBooks");
        assert_eq!(camel("list_books"), "listBooks");
    }
}
